added Task60 PageObject
ChristinaAstashkevich/Task60PO pull request #1
Opened 2017-07-07 13:05 UTC by ChristinaAstashkevich

2017-08-01 12:09 UTC, WGLife commented on pom.xml
> +            <groupId>org.seleniumhq.selenium</groupId>
Please, use the latest selenium version (3.4.0)

2017-08-01 12:20 UTC, EugenBorisik requested changes

2017-08-01 12:20 UTC, WGLife commented on src/main/java/core/TestBase.java
> +        driver.manage().timeouts().implicitlyWait(40, TimeUnit.SECONDS);
40 seconds for implicit waiter is too much, please decrease to <=10 seconds.

2017-08-01 12:20 UTC, WGLife commented on src/main/java/core/TestBase.java
> +        driver.get("https://mail.ru/");
Move string to constants.

2017-08-01 12:20 UTC, WGLife commented on src/main/java/core/WebBrowser.java
> +            System.setProperty("webdriver.chrome.driver", ".\\drivers\\chromedriver.exe");
This property doesn't work for me and I can't execute tests, please update.

2017-08-01 12:20 UTC, WGLife commented on src/main/java/page/LoginPage.java
> +    protected WebDriver driver = WebBrowser.getInstance();
Why the field is protected?

2017-08-01 12:20 UTC, WGLife commented on src/main/java/page/LoginPage.java
> +    private static By loginButton = By.id("mailbox__auth__button");
Please, make all By fields as constants.

2017-08-01 12:20 UTC, WGLife commented on src/main/java/page/LoginPage.java
> +        return driver.findElement(loginButton).isDisplayed();
"driver.findElement(loginButton)" is used at least twice, create private method for that line.

2017-08-01 12:20 UTC, WGLife commented on src/main/java/page/MailBoxPage.java
> +    protected WebDriver driver = WebBrowser.getInstance();
Why the field is protected?

2017-08-01 12:20 UTC, WGLife commented on src/main/java/page/MailBoxPage.java
> +    private static By logoutLink = By.cssSelector("#PH_logoutLink");
1. Make all By fields as constants
2. By.cssSelector("#PH_logoutLink") -> By.id(...)

2017-08-01 12:20 UTC, WGLife commented on src/main/java/page/MailBoxPage.java
> +    public WebElement getComposeButton(){
Why this method is public?
Optional: getComposeButton() and getLogoutLink() is excess, because methods are used only once. It's better to add such methods only when really is needed.

2017-08-01 12:20 UTC, WGLife commented on src/test/java/MailRuTest.java
> +    private String password = "060788avavav";
Please make this fields as constants

2017-08-03 18:28 UTC, ChristinaAstashkevich commented on pom.xml
> +            <groupId>org.seleniumhq.selenium</groupId>
updated

2017-08-03 18:35 UTC, ChristinaAstashkevich commented on src/main/java/core/WebBrowser.java
> +            System.setProperty("webdriver.chrome.driver", ".\\drivers\\chromedriver.exe");
Have no idea, why does this not working for you.
I have added folder with drivers and relative (short) path to this folder.

2017-08-03 18:36 UTC, ChristinaAstashkevich commented on src/main/java/page/LoginPage.java
> +    protected WebDriver driver = WebBrowser.getInstance();
Changed to private

2017-08-03 18:36 UTC, ChristinaAstashkevich commented on src/main/java/page/LoginPage.java
> +    private static By loginButton = By.id("mailbox__auth__button");
fixed

2017-08-03 18:37 UTC, ChristinaAstashkevich commented on src/main/java/page/LoginPage.java
> +        return driver.findElement(loginButton).isDisplayed();
added get-methods for login field, password field, login button

2017-08-03 18:38 UTC, ChristinaAstashkevich commented on src/main/java/page/LoginPage.java
> +        return driver.findElement(loginButton).isDisplayed();
changed relative methods as well

2017-08-03 18:38 UTC, ChristinaAstashkevich commented on src/main/java/page/MailBoxPage.java
> +    protected WebDriver driver = WebBrowser.getInstance();
changed to private

2017-08-03 18:38 UTC, ChristinaAstashkevich commented on src/main/java/page/MailBoxPage.java
> +    private static By logoutLink = By.cssSelector("#PH_logoutLink");
fixed

2017-08-03 18:40 UTC, ChristinaAstashkevich commented on src/main/java/page/MailBoxPage.java
> +    public WebElement getComposeButton(){
removed excess methods, updated relative methods

2017-08-03 18:40 UTC, ChristinaAstashkevich commented on src/test/java/MailRuTest.java
> +    private String password = "060788avavav";
updated

2017-08-07 07:24 UTC, WGLife commented on src/main/java/core/WebBrowser.java
> +            System.setProperty("webdriver.chrome.driver", ".\\drivers\\chromedriver.exe");
It was not working, because you didn't add drivers. Now it works

2017-08-07 07:31 UTC, EugenBorisik approved these changes

2017-08-07 07:31 UTC, merged